[profile.default]
src = "contracts/src"
test = "contracts/test"
script = "contracts/script"
out = "out"
libs = ["node_modules"]
remappings = ["@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/"]
auto_detect_remappings = false
ast = true
solc_version = "0.8.30"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
fs_permissions = [{ access = "read-write", path = "./deployments" }]

[profile.default.fuzz]
runs = 256

[profile.ci.fuzz]
runs = 2048
