import { parseAbi } from "viem";
export const tokenAbi = parseAbi([
  "function decimals() view returns (uint8)",
  "function balanceOf(address) view returns (uint256)",
  "function totalSupply() view returns (uint256)",
  "function allowance(address,address) view returns (uint256)",
  "function approve(address,uint256) returns (bool)",
  "function transfer(address,uint256) returns (bool)",
  "event Approval(address indexed owner,address indexed spender,uint256 value)",
  "function delegate(address)",
  "function delegates(address) view returns (address)",
  "function getVotes(address) view returns (uint256)",
  "function getPastVotes(address,uint256) view returns (uint256)",
  "function getPastTotalSupply(uint256) view returns (uint256)",
  "event Transfer(address indexed from,address indexed to,uint256 value)",
  "event DelegateChanged(address indexed delegator,address indexed fromDelegate,address indexed toDelegate)",
  "event DelegateVotesChanged(address indexed delegate,uint256 previousVotes,uint256 newVotes)",
]);
export const governorAbi = parseAbi([
  "function token() view returns (address)",
  "function getVotes(address,uint256) view returns (uint256)",
  "function hasVoted(uint256,address) view returns (bool)",
  "function propose(address[],uint256[],bytes[],string) returns (uint256)",
  "function hashProposal(address[],uint256[],bytes[],bytes32) pure returns (uint256)",
  "function castVote(uint256,uint8) returns (uint256)",
  "function execute(address[],uint256[],bytes[],bytes32) payable returns (uint256)",
  "function cancel(address[],uint256[],bytes[],bytes32) returns (uint256)",
  "function state(uint256) view returns (uint8)",
  "function proposalVotes(uint256) view returns (uint256 againstVotes,uint256 forVotes,uint256 abstainVotes)",
  "function quorum(uint256) view returns (uint256)",
  "function quorumNumerator() view returns (uint256)",
  "function quorumDenominator() view returns (uint256)",
  "function COUNTING_MODE() view returns (string)",
  "function proposalSnapshot(uint256) view returns (uint256)",
  "function proposalDeadline(uint256) view returns (uint256)",
  "function votingDelay() view returns (uint256)",
  "function votingPeriod() view returns (uint256)",
  "function proposalThreshold() view returns (uint256)",
  "function setVotingDelay(uint256)",
  "function setVotingPeriod(uint256)",
  "function setProposalThreshold(uint256)",
  "function updateQuorumNumerator(uint256)",
  "event ProposalCreated(uint256 proposalId,address proposer,address[] targets,uint256[] values,string[] signatures,bytes[] calldatas,uint256 voteStart,uint256 voteEnd,string description)",
  "event VoteCast(address indexed voter,uint256 proposalId,uint8 support,uint256 weight,string reason)",
  "event ProposalQueued(uint256 proposalId,uint256 etaSeconds)",
  "event ProposalExecuted(uint256 proposalId)",
  "event ProposalCanceled(uint256 proposalId)",
]);
export const ragequitAbi = parseAbi([
  "function treasury() view returns (address)",
  "function mana() view returns (address)",
  "function basket() view returns (address[3])",
  "function previewRedeem(uint256) view returns (uint256[3])",
  "function redeem(uint256,address,uint256[3],uint256) returns (uint256[3])",
  "event RagequitExecuted(address indexed member,address indexed recipient,uint256 manaBurned,uint256 gemPaid,uint256 wethPaid,uint256 usdcPaid)",
]);
// Historical V2 vault ABI is retained for decoding old drafts and events only.
export const vaultAbi = parseAbi([
  "function previewRedeem(uint256) view returns (uint256[3])",
  "function redeem(uint256,address,uint256[3],uint256) returns (uint256[3])",
  "function payNative(address,uint256)",
  "function payToken(address,address,uint256)",
  "event NativeDeposit(address indexed sender,uint256 amount)",
  "event Redeemed(address indexed member,address indexed recipient,uint256 manaBurned,uint256 polPaid,uint256 wethPaid,uint256 usdcPaid)",
  "event Payment(address indexed asset,address indexed recipient,uint256 amount)",
]);
export const ballotsAbi = parseAbi([
  "function createBallot(string,string[]) returns (uint256)",
  "function castVote(uint256,uint8) returns (uint256)",
  "function cancel(uint256)",
  "function state(uint256) view returns (uint8)",
  "function ballots(uint256) view returns (address author,uint48 snapshot,uint48 deadline,uint8 optionCount,uint8 quorumPercent,bool canceled,uint256 totalVotes)",
  "function result(uint256) view returns (uint8 winner,bool quorumReached,bool tied)",
  "function optionVotes(uint256,uint8) view returns (uint256)",
  "function setRules(uint48,uint32,uint256,uint8)",
  "event BallotCreated(uint256 indexed ballotId,address indexed author,string description,string[] options,uint48 snapshot,uint48 deadline,uint256 threshold,uint8 quorumPercent)",
  "event BallotVoteCast(uint256 indexed ballotId,address indexed voter,uint8 option,uint256 weight)",
  "event BallotCanceled(uint256 indexed ballotId)",
  "event RulesUpdated(uint48 delay,uint32 period,uint256 threshold,uint8 quorumPercent)",
]);
export const timelockAbi = parseAbi([
  "function getMinDelay() view returns (uint256)",
  "function updateDelay(uint256)",
  "event CallScheduled(bytes32 indexed id,uint256 indexed index,address target,uint256 value,bytes data,bytes32 predecessor,uint256 delay)",
  "event CallExecuted(bytes32 indexed id,uint256 indexed index,address target,uint256 value,bytes data)",
  "event Cancelled(bytes32 indexed id)",
  "event MinDelayChange(uint256 oldDuration,uint256 newDuration)",
  "event RoleGranted(bytes32 indexed role,address indexed account,address indexed sender)",
  "event RoleRevoked(bytes32 indexed role,address indexed account,address indexed sender)",
]);
export const allEvents = [
  ...ragequitAbi,
  ...tokenAbi,
  ...governorAbi,
  ...vaultAbi,
  ...ballotsAbi,
  ...timelockAbi,
].filter((x) => x.type === "event");
